package cn.hd.mapper;

import java.util.List;

import cn.hd.model.Data;

public interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    int insert(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    int insertSelective(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    Data selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    int updateByPrimaryKeySelective(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    int updateByPrimaryKey(Data record);

	List<Data> queryAll();
}