package cn.hd.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.hd.model.HandleHistory;

public interface HandleHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handleworkhistory
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handleworkhistory
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    int insert(HandleHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handleworkhistory
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    int insertSelective(HandleHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handleworkhistory
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    HandleHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handleworkhistory
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    int updateByPrimaryKeySelective(HandleHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_handleworkhistory
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    int updateByPrimaryKey(HandleHistory record);
/**
 * 查出所有这个工单的处理过的处理人
 * @param workid
 * @param userid
 * @return
 */
    /**
	 * 查出所有这个工单的处理过的处理人 （退单时要用用）
	 * @param workid
	 * @return
	 */
    List<HandleHistory> findHistoryByWorkid(@Param("workid")String workid,@Param("userid")int userid);
/**
 * 根据工单编号 查询历史信息
 * @param workid
 * @return
 */
	List<HandleHistory> queryByWorkid(String workid);
}