package cn.hd.mapper;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.hd.model.BaseConditionVO;
import cn.hd.model.Rolebean;


public interface RolebeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    int insert(Rolebean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    int insertSelective(Rolebean record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    Rolebean selectByPrimaryKey(Integer rid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    int updateByPrimaryKeySelective(Rolebean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    int updateByPrimaryKey(Rolebean record);
    /**
     * 查询所有
     * @return
     */
    List<Rolebean> queryAll();

	List<Rolebean> query(BaseConditionVO vo);
     /**
      * 保存角色与菜单的中间表
      * @param rid
      * @param mid
      */
	void saveRidAndMid(@Param("rid")Integer rid,@Param("mid") Integer mid);
     /**
      * 根据角色id取出这个角色所拥有的菜单(权限)
      * @param id
      * @return
      */
	List<Integer> findMidsByRid(int id);
    /**
     * 根据角色id先删除中间表
     * @param rid
     */
	void deleteRidAndMidByRid(Integer rid);
    
}