package cn.hd.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.hd.model.BaseConditionVO;
import cn.hd.model.Userbean;

public interface UserbeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    int insert(Userbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    int insertSelective(Userbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    Userbean selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    int updateByPrimaryKeySelective(Userbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    int updateByPrimaryKey(Userbean record);

	List<Userbean> query(BaseConditionVO vo);
/**
 * 保存到中间表
 * @param 用户userid
 * @param 角色rid
 */
void insertUseridAndRid(@Param("userid") Integer userid, @Param("rid")Integer rid);
/**
 * 根据ID删除中间表
 * @param userid
 */
void deleteUseridAndRidByUserid(Integer userid);
/**
 * 根据ID取出这个用户所拥有的的角色信息
 * @param id
 * @return
 */
List<Integer> findRidsByUserid(int id);

/**
 * 根据用户名到数据库中查询，如果有记录，就表示已经存在
 * @param username
 * @return
 */
Userbean findByUsername(String username);
/**
 * 根据部门id找出这个部门下所有的用户列表 
 * @param did
 * @return
 */

List<Userbean> queryUserByDid(int did);
}