package cn.hd.mapper;

import java.util.List;

import cn.hd.model.Workorder;

public interface WorkorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workorder
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    int deleteByPrimaryKey(String workorderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workorder
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    int insert(Workorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workorder
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    int insertSelective(Workorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workorder
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    Workorder selectByPrimaryKey(String workorderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workorder
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    int updateByPrimaryKeySelective(Workorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workorder
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    int updateByPrimaryKey(Workorder record);
    /**
     * 查询
     * @param work
     * @return
     */
	List<Workorder> query(Workorder work);
}