package cn.hd.mapper;

import cn.hd.model.Workattach;

public interface WorkattachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workattach
     *
     * @mbggenerated Fri Apr 14 14:03:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workattach
     *
     * @mbggenerated Fri Apr 14 14:03:53 CST 2017
     */
    int insert(Workattach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workattach
     *
     * @mbggenerated Fri Apr 14 14:03:53 CST 2017
     */
    int insertSelective(Workattach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workattach
     *
     * @mbggenerated Fri Apr 14 14:03:53 CST 2017
     */
    Workattach selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workattach
     *
     * @mbggenerated Fri Apr 14 14:03:53 CST 2017
     */
    int updateByPrimaryKeySelective(Workattach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_workattach
     *
     * @mbggenerated Fri Apr 14 14:03:53 CST 2017
     */
    int updateByPrimaryKey(Workattach record);
}