package cn.hd.model;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customername
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.sex
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.certificatetype
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String certificatetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.centificatenumber
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String centificatenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.telephone
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.wechatwhite
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String wechatwhite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.openchannel
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String openchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.qqwhile
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String qqwhile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customertype
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String customertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.comeinchannel
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String comeinchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.callphone
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String callphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customername
     *
     * @return the value of t_customer.customername
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customername
     *
     * @param customername the value for t_customer.customername
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.sex
     *
     * @return the value of t_customer.sex
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.sex
     *
     * @param sex the value for t_customer.sex
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.certificatetype
     *
     * @return the value of t_customer.certificatetype
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getCertificatetype() {
        return certificatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.certificatetype
     *
     * @param certificatetype the value for t_customer.certificatetype
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setCertificatetype(String certificatetype) {
        this.certificatetype = certificatetype == null ? null : certificatetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.centificatenumber
     *
     * @return the value of t_customer.centificatenumber
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getCentificatenumber() {
        return centificatenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.centificatenumber
     *
     * @param centificatenumber the value for t_customer.centificatenumber
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setCentificatenumber(String centificatenumber) {
        this.centificatenumber = centificatenumber == null ? null : centificatenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.telephone
     *
     * @return the value of t_customer.telephone
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.telephone
     *
     * @param telephone the value for t_customer.telephone
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.wechatwhite
     *
     * @return the value of t_customer.wechatwhite
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getWechatwhite() {
        return wechatwhite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.wechatwhite
     *
     * @param wechatwhite the value for t_customer.wechatwhite
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setWechatwhite(String wechatwhite) {
        this.wechatwhite = wechatwhite == null ? null : wechatwhite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.openchannel
     *
     * @return the value of t_customer.openchannel
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getOpenchannel() {
        return openchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.openchannel
     *
     * @param openchannel the value for t_customer.openchannel
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setOpenchannel(String openchannel) {
        this.openchannel = openchannel == null ? null : openchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.qqwhile
     *
     * @return the value of t_customer.qqwhile
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getQqwhile() {
        return qqwhile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.qqwhile
     *
     * @param qqwhile the value for t_customer.qqwhile
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setQqwhile(String qqwhile) {
        this.qqwhile = qqwhile == null ? null : qqwhile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customertype
     *
     * @return the value of t_customer.customertype
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getCustomertype() {
        return customertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customertype
     *
     * @param customertype the value for t_customer.customertype
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setCustomertype(String customertype) {
        this.customertype = customertype == null ? null : customertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.comeinchannel
     *
     * @return the value of t_customer.comeinchannel
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getComeinchannel() {
        return comeinchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.comeinchannel
     *
     * @param comeinchannel the value for t_customer.comeinchannel
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setComeinchannel(String comeinchannel) {
        this.comeinchannel = comeinchannel == null ? null : comeinchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.callphone
     *
     * @return the value of t_customer.callphone
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getCallphone() {
        return callphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.callphone
     *
     * @param callphone the value for t_customer.callphone
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setCallphone(String callphone) {
        this.callphone = callphone == null ? null : callphone.trim();
    }
}