package cn.hd.model;

import java.util.Date;

public class HandleHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_handleworkhistory.id
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_handleworkhistory.workorderid
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    private String workorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_handleworkhistory.handleperson
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    private Integer handleperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_handleworkhistory.handlepersonname
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    private String handlepersonname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_handleworkhistory.handlegroup
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    private Integer handlegroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_handleworkhistory.handlegroupname
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    private String handlegroupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_handleworkhistory.actionstr
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    private String actionstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_handleworkhistory.createdate
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_handleworkhistory.descs
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    private String descs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_handleworkhistory.id
     *
     * @return the value of t_handleworkhistory.id
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_handleworkhistory.id
     *
     * @param id the value for t_handleworkhistory.id
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_handleworkhistory.workorderid
     *
     * @return the value of t_handleworkhistory.workorderid
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public String getWorkorderid() {
        return workorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_handleworkhistory.workorderid
     *
     * @param workorderid the value for t_handleworkhistory.workorderid
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public void setWorkorderid(String workorderid) {
        this.workorderid = workorderid == null ? null : workorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_handleworkhistory.handleperson
     *
     * @return the value of t_handleworkhistory.handleperson
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public Integer getHandleperson() {
        return handleperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_handleworkhistory.handleperson
     *
     * @param handleperson the value for t_handleworkhistory.handleperson
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public void setHandleperson(Integer handleperson) {
        this.handleperson = handleperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_handleworkhistory.handlepersonname
     *
     * @return the value of t_handleworkhistory.handlepersonname
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public String getHandlepersonname() {
        return handlepersonname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_handleworkhistory.handlepersonname
     *
     * @param handlepersonname the value for t_handleworkhistory.handlepersonname
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public void setHandlepersonname(String handlepersonname) {
        this.handlepersonname = handlepersonname == null ? null : handlepersonname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_handleworkhistory.handlegroup
     *
     * @return the value of t_handleworkhistory.handlegroup
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public Integer getHandlegroup() {
        return handlegroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_handleworkhistory.handlegroup
     *
     * @param handlegroup the value for t_handleworkhistory.handlegroup
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public void setHandlegroup(Integer handlegroup) {
        this.handlegroup = handlegroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_handleworkhistory.handlegroupname
     *
     * @return the value of t_handleworkhistory.handlegroupname
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public String getHandlegroupname() {
        return handlegroupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_handleworkhistory.handlegroupname
     *
     * @param handlegroupname the value for t_handleworkhistory.handlegroupname
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public void setHandlegroupname(String handlegroupname) {
        this.handlegroupname = handlegroupname == null ? null : handlegroupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_handleworkhistory.actionstr
     *
     * @return the value of t_handleworkhistory.actionstr
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public String getActionstr() {
        return actionstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_handleworkhistory.actionstr
     *
     * @param actionstr the value for t_handleworkhistory.actionstr
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public void setActionstr(String actionstr) {
        this.actionstr = actionstr == null ? null : actionstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_handleworkhistory.createdate
     *
     * @return the value of t_handleworkhistory.createdate
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_handleworkhistory.createdate
     *
     * @param createdate the value for t_handleworkhistory.createdate
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_handleworkhistory.descs
     *
     * @return the value of t_handleworkhistory.descs
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_handleworkhistory.descs
     *
     * @param descs the value for t_handleworkhistory.descs
     *
     * @mbggenerated Mon Apr 17 11:42:36 CST 2017
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }
}