package cn.hd.model;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.MID
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.MENUNAME
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.PID
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.ISDEL
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    private Integer isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.ORDERID
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.SECURITYNAME
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    private String securityname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.MID
     *
     * @return the value of t_menu.MID
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.MID
     *
     * @param mid the value for t_menu.MID
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.MENUNAME
     *
     * @return the value of t_menu.MENUNAME
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.MENUNAME
     *
     * @param menuname the value for t_menu.MENUNAME
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.PID
     *
     * @return the value of t_menu.PID
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.PID
     *
     * @param pid the value for t_menu.PID
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.ISDEL
     *
     * @return the value of t_menu.ISDEL
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.ISDEL
     *
     * @param isdel the value for t_menu.ISDEL
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.ORDERID
     *
     * @return the value of t_menu.ORDERID
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.ORDERID
     *
     * @param orderid the value for t_menu.ORDERID
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.SECURITYNAME
     *
     * @return the value of t_menu.SECURITYNAME
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public String getSecurityname() {
        return securityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.SECURITYNAME
     *
     * @param securityname the value for t_menu.SECURITYNAME
     *
     * @mbggenerated Tue Apr 11 15:54:34 CST 2017
     */
    public void setSecurityname(String securityname) {
        this.securityname = securityname == null ? null : securityname.trim();
    }
}