package cn.hd.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Userbean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USERID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.USERNAME
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PASSWORD
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.REALNAME
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.DID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.JID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private Integer jid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.OPENTIME
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private Date opentime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.SEX
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.CITY
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.PID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.TELEPHONE
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.EMAIL
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.MOBILE
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ADDRESS
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.MARRIED
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private Integer married;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.salt
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    private String salt;

    private List<Integer>  rids=new ArrayList<>();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.USERID
     *
     * @return the value of t_user.USERID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.USERID
     *
     * @param userid the value for t_user.USERID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.USERNAME
     *
     * @return the value of t_user.USERNAME
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.USERNAME
     *
     * @param username the value for t_user.USERNAME
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PASSWORD
     *
     * @return the value of t_user.PASSWORD
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PASSWORD
     *
     * @param password the value for t_user.PASSWORD
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.REALNAME
     *
     * @return the value of t_user.REALNAME
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.REALNAME
     *
     * @param realname the value for t_user.REALNAME
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.DID
     *
     * @return the value of t_user.DID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.DID
     *
     * @param did the value for t_user.DID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.JID
     *
     * @return the value of t_user.JID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public Integer getJid() {
        return jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.JID
     *
     * @param jid the value for t_user.JID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setJid(Integer jid) {
        this.jid = jid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.OPENTIME
     *
     * @return the value of t_user.OPENTIME
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public Date getOpentime() {
        return opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.OPENTIME
     *
     * @param opentime the value for t_user.OPENTIME
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setOpentime(Date opentime) {
        this.opentime = opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.SEX
     *
     * @return the value of t_user.SEX
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.SEX
     *
     * @param sex the value for t_user.SEX
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.CITY
     *
     * @return the value of t_user.CITY
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.CITY
     *
     * @param city the value for t_user.CITY
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.PID
     *
     * @return the value of t_user.PID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.PID
     *
     * @param pid the value for t_user.PID
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.TELEPHONE
     *
     * @return the value of t_user.TELEPHONE
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.TELEPHONE
     *
     * @param telephone the value for t_user.TELEPHONE
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.EMAIL
     *
     * @return the value of t_user.EMAIL
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.EMAIL
     *
     * @param email the value for t_user.EMAIL
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.MOBILE
     *
     * @return the value of t_user.MOBILE
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.MOBILE
     *
     * @param mobile the value for t_user.MOBILE
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ADDRESS
     *
     * @return the value of t_user.ADDRESS
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ADDRESS
     *
     * @param address the value for t_user.ADDRESS
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.MARRIED
     *
     * @return the value of t_user.MARRIED
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public Integer getMarried() {
        return married;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.MARRIED
     *
     * @param married the value for t_user.MARRIED
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setMarried(Integer married) {
        this.married = married;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.salt
     *
     * @return the value of t_user.salt
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.salt
     *
     * @param salt the value for t_user.salt
     *
     * @mbggenerated Tue Apr 11 17:23:49 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

	public List<Integer> getRids() {
		return rids;
	}

	public void setRids(List<Integer> rids) {
		this.rids = rids;
	}	
    
}