package cn.hd.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Workorder extends BaseConditionVO{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.workorderid
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String workorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.customerid
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.customername
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.centificatenumber
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String centificatenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.aging
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private Integer aging;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.problemtype
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private String problemtype;
    private String problemtypeName; //为方便查询 而临时加的属性名，在数据库中没有这个字段
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.handlegroup
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private Integer handlegroup;
    private String handlegroupName; //为方便查询 而临时加的属性名，在数据库中没有这个字段
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.handleperson
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private Integer handleperson;
    private String handlepersonName; //为方便查询 而临时加的属性名，在数据库中没有这个字段
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.urgencylevel
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */	
    private String urgencylevel;
    private String urgencylevelName; //为方便查询 而临时加的属性名，在数据库中没有这个字段

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.status
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private Integer status;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_workorder.creatdate
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    private Date creatdate;
    private Customer customer;
    
    //一个工单对应多个附件
    private List<Workattach> attaches=new ArrayList<>();

    private String descs;//临时属性
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.workorderid
     *
     * @return the value of t_workorder.workorderid
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getWorkorderid() {
        return workorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.workorderid
     *
     * @param workorderid the value for t_workorder.workorderid
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setWorkorderid(String workorderid) {
        this.workorderid = workorderid == null ? null : workorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.customerid
     *
     * @return the value of t_workorder.customerid
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.customerid
     *
     * @param customerid the value for t_workorder.customerid
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.customername
     *
     * @return the value of t_workorder.customername
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.customername
     *
     * @param customername the value for t_workorder.customername
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.centificatenumber
     *
     * @return the value of t_workorder.centificatenumber
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getCentificatenumber() {
        return centificatenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.centificatenumber
     *
     * @param centificatenumber the value for t_workorder.centificatenumber
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setCentificatenumber(String centificatenumber) {
        this.centificatenumber = centificatenumber == null ? null : centificatenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.aging
     *
     * @return the value of t_workorder.aging
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public Integer getAging() {
        return aging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.aging
     *
     * @param aging the value for t_workorder.aging
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setAging(Integer aging) {
        this.aging = aging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.problemtype
     *
     * @return the value of t_workorder.problemtype
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getProblemtype() {
        return problemtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.problemtype
     *
     * @param problemtype the value for t_workorder.problemtype
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setProblemtype(String problemtype) {
        this.problemtype = problemtype == null ? null : problemtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.handlegroup
     *
     * @return the value of t_workorder.handlegroup
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public Integer getHandlegroup() {
        return handlegroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.handlegroup
     *
     * @param handlegroup the value for t_workorder.handlegroup
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setHandlegroup(Integer handlegroup) {
        this.handlegroup = handlegroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.handleperson
     *
     * @return the value of t_workorder.handleperson
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public Integer getHandleperson() {
        return handleperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.handleperson
     *
     * @param handleperson the value for t_workorder.handleperson
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setHandleperson(Integer handleperson) {
        this.handleperson = handleperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.urgencylevel
     *
     * @return the value of t_workorder.urgencylevel
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public String getUrgencylevel() {
        return urgencylevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.urgencylevel
     *
     * @param urgencylevel the value for t_workorder.urgencylevel
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setUrgencylevel(String urgencylevel) {
        this.urgencylevel = urgencylevel == null ? null : urgencylevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.status
     *
     * @return the value of t_workorder.status
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.status
     *
     * @param status the value for t_workorder.status
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_workorder.creatdate
     *
     * @return the value of t_workorder.creatdate
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public Date getCreatdate() {
        return creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_workorder.creatdate
     *
     * @param creatdate the value for t_workorder.creatdate
     *
     * @mbggenerated Fri Apr 14 09:14:35 CST 2017
     */
    public void setCreatdate(Date creatdate) {
        this.creatdate = creatdate;
    }

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public List<Workattach> getAttaches() {
		return attaches;
	}

	public void setAttaches(List<Workattach> attaches) {
		this.attaches = attaches;
	}

	public String getHandlegroupName() {
		return handlegroupName;
	}

	public void setHandlegroupName(String handlegroupName) {
		this.handlegroupName = handlegroupName;
	}

	public String getHandlepersonName() {
		return handlepersonName;
	}

	public void setHandlepersonName(String handlepersonName) {
		this.handlepersonName = handlepersonName;
	}

	public String getUrgencylevelName() {
		return urgencylevelName;
	}

	public void setUrgencylevelName(String urgencylevelName) {
		this.urgencylevelName = urgencylevelName;
	}

	public String getProblemtypeName() {
		return problemtypeName;
	}

	public void setProblemtypeName(String problemtypeName) {
		this.problemtypeName = problemtypeName;
	}

	public String getDescs() {
		return descs;
	}

	public void setDescs(String descs) {
		this.descs = descs;
	}
    
}